AWS_ACCESS_KEY_ID: AKIAJZRQVQEOCK5SBEUA
AWS_SECRET_ACCESS_KEY: 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
S3_BUCKET_NAME: skunkwerx
FRESHBOOKS_KEY: 23b44f2982b948cd656a7126f70d5f51
FRESHBOOKS_URL: https://skunkwerxperformanceautomotivellc.freshbooks.com/api/2.1/xml-in
MAILER_USERNAME: clay.morton
MAILER_PASSWORD: PissedOff76